### ISSUE TITLE
请问, 这个都同步了那些配置. 能否详细的说明一下?

### ISSUE THREAD

**Issue by qiuyimo** [ddrccw/mac-config#1]
公司里使用的是`mac mini`, 和家里的`mac`, 如何能同步一些`app`的配置呢 ? 

如`iTerm2`, `alfred`等等.

**Comment by ddrccw** [comment]
iTerm2 `General`-`Preferences`可以指定加载Preference路径
alfred也有类似的功能吧

另外这个仓库只是用来同步我个人开发常用的一些配置，不具有普适性。

**Comment by qiuyimo** [comment]
@ddrccw 好的, 谢谢.
